name: Daily Commit

on:
  schedule:
    - cron: '0 9 * * *'   # Runs every day at 9 AM UTC
  workflow_dispatch:

permissions:
  contents: write   # ✅ Give workflow permission to push changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update log file
        run: |
          echo "Updated on $(date)" >> log.txt

      - name: Commit changes
        run: |
          git config --global user.name "SATHASHINI-S"
          git config --global user.email "sathashini4623@gmail.com"
          git add log.txt
          git commit -m "Daily update: $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ✅ Use built-in token

